Repository FISCO-BCOS/FISCO-BCOS-DOC, pull requests merged in 2022-01, with the labels that each got.

#1381 <doc>(2.x): fix 2.x version git checkout.
  2.x/docs/manual/data_governance.md
  2.x/docs/sdk/java_sdk/amop.md
  2.x/docs/sdk/java_sdk/quick_start.md
  2.x/docs/tutorial/cdn.md
  2.x/docs/tutorial/stress_testing.md
  2.x/docs/tutorial/use_hsm.md
  2.x/en/docs/manual/cdn.md
  2.x/en/docs/manual/get_executable.md
Labels: bug fix, v2.x, git repo

#1380 Update crypto.md
  2.x/docs/sdk/java_sdk/crypto.md
Labels: bug fix, misspelling

#1383 Update storage_security.md
  2.x/docs/design/features/storage_security.md
Labels: misspelling
