Repository FISCO-BCOS/FISCO-BCOS-DOC, pull requests merged in 2022-03, with the labels that each got.

#1415 Update crypto.md
  2.x/docs/sdk/java_sdk/crypto.md
Labels: enhancement, v2.x

#1414 <doc>(2.x,3.x): fix macOS homebrew install openssl error.
  2.x/docs/installation.md
  2.x/docs/manual/get_executable.md
  2.x/docs/manual/group_use_cases.md
  2.x/docs/tutorial/compile.md
  3.x/zh_CN/docs/develop/sdk/c_sdk/env.md
  3.x/zh_CN/docs/quick_start/air_installation.md
Labels: Operational optimization

#1412 Update installation.md
  2.x/docs/installation.md
Labels: enhancement
